---
- name: Decide which Debian release to use
  set_fact:
    java8_apt_release: '{% if ansible_distribution_release == "jessie" %}jessie-backports{% else %}{{ ansible_distribution_release }}{% endif %}'

- name: install jessie-backports
  include_role:
    name: apt-repositories
  vars:
    apt_repositories_install_backports: True
  when: ansible_distribution_release == "jessie"

- name: Java 8 is installed
  apt:
    name: openjdk-8-jre
    default_release: "{{ java8_apt_release }}"
    state: present
  when: ansible_distribution_release == "jessie"
  tags:
    - java
    - packages

- name: Java 8 is the default alternative
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  when: java8_default_alternative
  tags:
    - java
